---
- name: Setup Customer Chatbot Environment
  hosts: all
  become: yes
  vars:
    workspace_path: "/home/test/customer-chatbot"  # Change this to the desired path
    data_dir: "{{ workspace_path }}/data"
    output_dir: "{{ workspace_path }}/output"
    config_dir: "{{ workspace_path }}/config"
    conda_installer_url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    git_repo_url: "https://github.com/oneapi-src/customer-chatbot.git"
    conda_env_file: "{{ workspace_path }}/env/intel_env.yml"

  tasks:
    - name: Set environment variables
      set_fact:
        WORKSPACE: "{{ workspace_path }}"
        DATA_DIR: "{{ data_dir }}"
        OUTPUT_DIR: "{{ output_dir }}"
        CONFIG_DIR: "{{ config_dir }}"

    - name: Install git
      apt:
        name: git
        state: present
      register: git_installed

    - name: Find git executable
      command: which git
      register: git_path
      when: git_installed is changed

    - name: Create workspace directory
      file:
        path: "{{ workspace_path }}"
        state: directory


    - name: Clone Git repository
      command: "{{ git_path.stdout | default('/usr/bin/git') }} clone {{ git_repo_url }} {{ workspace_path }}"
      args:
        creates: "{{ workspace_path }}/.git"
      environment:
        PATH: "{{ ansible_env.PATH }}"
      when: git_path.stat.exists or git_installed is changed