---
- name: Setup Customer Chatbot Environment
  hosts: all
  become: yes
  vars:
    workspace_path: "/home/test/customer-chatbot"  # Change this to the desired path
    data_dir: "{{ workspace_path }}/data"
    output_dir: "{{ workspace_path }}/output"
    config_dir: "{{ workspace_path }}/config"
    conda_installer_url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    git_repo_url: "https://github.com/oneapi-src/customer-chatbot.git"
    conda_env_file: "{{ workspace_path }}/env/intel_env.yml"

  tasks:
    - name: Activate Miniconda environment and print Python package versions
      become: yes
      shell: |
        conda activate customer_chatbot_intel
        python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__);"
      register: python_output
      args:
        executable: /bin/bash
      environment:
        PATH: "/opt/miniconda3/bin:{{ ansible_env.PATH }}"

    - name: Print the output
      debug:
        msg: "{{ python_output.stdout }}"